### ISSUE TITLE
BonziWORLD Sockets Get Failed To Load Resource

### ISSUE THREAD

**Issue by kiko1512** [Joseph14078/BonziWORLD#8]
Failed to load resource: the server responded with a status of 404 (Not Found)

GET http://bonziworld.com:3000/socket.io/?EIO=3&transport=polling&t=MWDocQE net::ERR_CONNECTION_REFUSED

Failed to load resource: net::ERR_CONNECTION_REFUSED

Can you come back?

1st Not loading ever on 14th Jan 2018 will shut down forever to 9th Feb 2018
2nd Not Loading Ever On 1th May 2018

**Comment by Joseph14078** [comment]
My apologies, it seems like the server process crashed on my end. I've revived it and will keep an eye on it.
